theme: jekyll-theme-minimal
title: Italian Reproducibility Network
description: a peer-led consortium that aims to investigate the factors that contribute to robust research and disseminate them within the Italian scientific community.
